### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by staycanuca** [cstoicescu/iptv-free-tv#1]
HI, I get this  error:

java.lang.IndexOutOfBoundsException: Index: 4, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at Main.main(Main.java:565)
Exception detected. Please close ALL existing Chrome, and try again

chromedrive   32    version 84
win 10
run as admin 
when I run but like admin , chrome is starting, go to all pages, but get 0 bytes m3u playlist

**Comment by cstoicescu** [comment]
I'm aware of this bug. 
It occurs sometimes when page is not fully loaded and it tries to get all WebElements, but some of them are not loaded. The fix is using a **implicit wait** or **explicit wait**. I could fix it using implicit wait but it would increase running time from 33 sec to 3 - 4 minutes, or using explicit wait, but it would takea lot of refactoring.

**Comment by cstoicescu** [comment]
I found a workaround, though exceptions are still thrown, it reruns the code, this way it would take a lot shorter. Maybe if i have time i will do the explicit wait, for now it works at intented. Please let me know if it works now.
**ALSO you can always download playlist.m3u it will work most of the time, i'll keep it updated, no need to run the api on your computer.**

**Comment by staycanuca** [comment]
Now is everything ok.
It's slower but is not a problem.  And now chromedriver run in background.
Thanks
