### ISSUE TITLE
List Update

### ISSUE THREAD

**Issue by patrickUCV** [cstoicescu/iptv-free-tv#3]
Update playlist with general tv station

**Comment by cstoicescu** [comment]
Write a list that containing the channels that you want and i'll try to update it this weeknd.

**Comment by patrickUCV** [comment]
Thanks@
1. TVR 1
2. TVR 2
3. TVR HD
4. PRO TV
5. PRO TV HD
6. Antena 1
7. Antena 1 HD
8. Kanal D
9. Kanal D HD
10. PRIMA TV
11. National TV
12. DIGI 24
13. DIGI 24 HD
14. Reaitatea
15. Antena 3
16. Antena 3 HD
17. RomaniaTV
18. B1
27. PRO X
28. PRO X HD
29. Eurosport
30. Eurosport HD
31. Eurosport 2
32. Eurosport 2 HD
33. PRO 2
34. PRO 2 HD
35. PRO GOLD
36. Happy Channel
37. Happy Channel HD
38. Antena Stars
39. Antena Stars HD

**Comment by cstoicescu** [comment]
O sa dureze ceva sa stii :). 2 3 sapt. Dar o sa le pun

**Comment by patrickUCV** [comment]
Nu-i nici o problema , oricum lista ta este buna . Daca poți pune astea pro
tv , antena ..astea mai comune ;)

Mulțumesc!

vin., 9 oct. 2020, 21:16 Stoicescu Catalin <notifications@github.com> a
scris:

**Comment by cstoicescu** [comment]
Am adaugat cateva canale mai importante
#EXTINF:-1,RO: ANTENA 1 new
#EXTINF:-1,RO: PROTV new
#EXTINF:-1,RO: DIGI 4K new
#EXTINF:-1,RO: PRO 2 new
#EXTINF:-1,RO: PRO X new
#EXTINF:-1,RO: ANTENA STARS new
#EXTINF:-1,RO: TVR 1 new


De restul chiar nu o sa mai am timp sa ma ocup urmatoarele luni. Probabil prin februarie martie.

**Comment by patrickUCV** [comment]
Este super, mulțumesc mult

dum., 11 oct. 2020, 18:15 Stoicescu Catalin <notifications@github.com> a
scris:

**Comment by patrickUCV** [comment]
Salut, îmi poți da un how to ( tutorial ) să mențin eu proiectul .chiar este bun . Mulțumesc anticipat !

**Comment by cstoicescu** [comment]
Nu cred ca ai cum, doar daca iti dau colab. Repoul o sa fie mereu actualizat automat de un script de pe laptopul personal, deci o sa mearga in continuare. 

Cand am spus ca V.1.7 e finala, m-am referit ca nu o sa mai lucrez la cod deloc, o sa incep probabil alt proiect. Acum e destul de stabil si am rezolvat toate bugurile.  Daca nu o sa mai functioneze vreodata poti sa lasi un issue aici si o sa ma uit.

So, no worries :) o sa fie functional mult si bine :), chiar daca nu o sa mai ma ocup de el, e automatizat.

**Comment by patrickUCV** [comment]
Ok super , mulțumesc.

**Comment by patrickUCV** [comment]
Salut , nu mai functioneaza 

Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 86.0.4240.193, chrome: {chromedriverVersion: 86.0.4240.22 (398b0743353ff..., userDataDir: C:\Users\crean\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:64962}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: e2f230028cabe312bd57fda3c4d35b8a
*** Element info: {Using=xpath, value=//*[contains(text(), 'Intrare»')]}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
        at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
        at Main.main(Main.java:81)
Exception detected. Please close ALL existing Chrome, and try again

**Comment by cstoicescu** [comment]
L-am inchis permanent.

Cineva a sesizat si am primit un DMCA notice de la Digi Romania, in care spun ca vor face o plangere penala la Parchetul de pe lângă Înalta Curte de Casație și Justiție pentru "sharing" de continut (adica canelele TV)  protejat de legislatia privind proprietatea intelectuala, daca nu incetez activitatea.

**Comment by Stefan121194** [comment]
salut am incarcat programele puse de tine pe IPTV insa imi porneste acel imn al moldovei sovietice :D si nu stiu cum pot reusi sa actualizez acea lista pentru ca e super facuta nota 10

**Comment by cstoicescu** [comment]
L-am inchis, citeste comentariul de mai sus si ai sa vezi de ce

> salut am incarcat programele puse de tine pe IPTV insa imi porneste acel imn al moldovei sovietice :D si nu stiu cum pot reusi sa actualizez acea lista pentru ca e super facuta nota 10
